# Conduit
version: '3'

services:
    homeserver:
        # use tag 'next' for current dev version, 'lastest' for stable
        image: matrixconduit/matrix-conduit:latest
        restart: unless-stopped
        ports:
             - 8448:6167
        volumes:
            - db:/srv/conduit/.local/share/conduit
            ### Uncomment if you want to use conduit.toml to configure Conduit
            ### Note: Set env vars will override conduit.toml value
            #- /opt/conduit/conduit.toml:/srv/conduit/conduit.toml
        environment:
            CONDUIT_SERVER_NAME: subdomain.domain  # replace with your own name
            CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
            CONDUIT_ALLOW_REGISTRATION: 'true'
            ### Uncomment and change values as desired
            CONDUIT_ADDRESS: 0.0.0.0
            CONDUIT_PORT: 6167
            CONDUIT_CONFIG: ''  # if you want to configure purely by env vars, set this to an empty string ''
            # Available levels are: error, warn, info, debug, trace - more info at: https://docs.rs/env_logger/*/env_logger/#enabling-logging
            # CONDUIT_LOG: trace  # default is: "info,rocket=off,_=off,sled=off"
            # CONDUIT_ALLOW_JAEGER: 'false'
            CONDUIT_ALLOW_ENCRYPTION: 'true'
            CONDUIT_ALLOW_FEDERATION: 'true'
            CONDUIT_DATABASE_PATH: /srv/conduit/.local/share/conduit
            # CONDUIT_WORKERS: 10
            # CONDUIT_MAX_REQUEST_SIZE: 20_000_000  # in bytes, ~20 MB
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.conduit-secure.rule=Host(`conduit.$MY_DOMAIN`)"
            - "traefik.http.routers.conduit-secure.entrypoints=https"
            - "traefik.http.routers.conduit-secure.tls.certresolver=http"
            - "traefik.http.routers.conduit-secure.middlewares=cors-headers@docker"
            - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*"
            - "traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=Origin, X-Requested-With, Content-Type, Accept, Authorization"
            - "traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=GET, POST, PUT, DELETE, OPTIONS"


    well-known:
        image: nginx:latest
        restart: unless-stopped
        volumes:
            - ./nginx/matrix.conf:/etc/nginx/conf.d/matrix.conf # the config to serve the .well-known/matrix files
            - ./nginx/www:/var/www/ # location of the client and server .well-known-files
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.matrix-secure.rule=Host(`conduit.$MY_DOMAIN`) && PathPrefix(`/.well-known/matrix`)"
            - "traefik.http.routers.matrix-secure.entrypoints=https"
            - "traefik.http.routers.matrix-secure.tls.certresolver=http"
            - "traefik.http.routers.matrix-secure.middlewares=cors-headers@docker"
            - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*"
            - "traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=Origin, X-Requested-With, Content-Type, Accept, Authorization"
            - "traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=GET, POST, PUT, DELETE, OPTIONS"

  
    ### Uncomment if you want to use your own Element-Web App.
    ### Note: You need to provide a config.json for Element and you also need a second
    ###       Domain or Subdomain for the communication between Element and Conduit
    ### Config-Docs: https://github.com/vector-im/element-web/blob/develop/docs/config.md
    # element-web:
    #     image: vectorim/element-web:latest
    #     restart: unless-stopped
    #     ports:
    #         - 8009:80
    #     volumes:
    #         - ./element_config.json:/app/config.json
    #     depends_on:
    #         - homeserver



volumes:
  db:

networks:
  default:
    external:
      name: $DEFAULT_NETWORK

